// This file was auto-generated by Fern from our API Definition.

/**
 * Error body returned with HTTP 409. The identifier you sent is well-formed but not unique: it names a real resource on more than one provider, and nothing in the request says which one you meant. Polymarket and Predict share both the bare-numeric and kebab-case identifier shapes and their id spaces genuinely overlap, so this is a routine outcome rather than an edge case — measured 2026-08-25, 53 of 93 Predict market ids drawn from `GET /v1/matching-markets/sports` also resolved on Polymarket.
 *
 * `candidates` lists exactly the providers the identifier resolved on, in a stable order, and every entry is a legal `?provider=` value. Retry the same identifier with `?provider={candidate}`, or with the composite `{provider}:{id}` form, and the lookup is deterministic. Clients that fan out over identifiers should handle 409 by re-issuing with the provider they already know from the listing that produced the id — every list and matching response that emits an identifier also emits its provider.
 */
export interface AmbiguousIdentifierError {
    /** Always `ambiguous_identifier`. */
    code: string;
    /** Human-readable detail naming the identifier, the providers it resolved on, and how to disambiguate. */
    message: string;
    /** The parameter holding the identifier, `market_id` or `event_id`. */
    param?: string;
    /** The providers this identifier resolved on. Each value is accepted verbatim by the `provider` query parameter. */
    candidates: string[];
    statusCode: number;
}
