// This file was auto-generated by Fern from our API Definition.

/**
 * Error body returned with HTTP 409. The identifier you sent is well-formed but not unique: it names a real resource on more than one platform, and nothing in the request says which one you meant. Polymarket and Predict share both the bare-numeric and kebab-case identifier shapes and their id spaces genuinely overlap, so this is a routine outcome rather than an edge case — measured 2026-08-25, 53 of 93 Predict market ids drawn from `GET /v1/matching-markets/sports` also resolved on Polymarket.
 *
 * `candidates` lists exactly the platforms the identifier resolved on, in a stable order, and every entry is a legal `?platform=` value. Retry the same identifier with `?platform={candidate}`, or with the composite `{platform}:{id}` form, and the lookup is deterministic. Clients that fan out over identifiers should handle 409 by re-issuing with the platform they already know from the listing that produced the id — every list and matching response that emits an identifier also emits its platform.
 */
export interface AmbiguousIdentifierError {
    /** Short machine-stable reason, e.g. `ambiguous market_id`. */
    error: string;
    /** Human-readable detail naming the identifier, the platforms it resolved on, and how to disambiguate. */
    message?: string;
    /** The platforms this identifier resolved on. Each value is accepted verbatim by the `platform` query parameter. */
    candidates: string[];
    statusCode: number;
}
