// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../index.js";

export interface CanonicalSportsSubmarket {
    /** Stable canonical submarket key within the event. */
    key: string;
    marketType: string;
    segment: string;
    displayName?: string;
    metric?: string;
    /** Unsigned threshold for totals and player props; signed handicap for spreads. Omitted for moneyline markets. */
    line?: number;
    /** Participant or player whose line is represented. Present for subject-owned markets such as spreads and player props; omitted for event-owned moneylines and totals. */
    subject?: PredictorSDK.CanonicalSportsSubject;
    rules?: PredictorSDK.CanonicalSportsRules;
    outcomes: PredictorSDK.CanonicalSportsOutcome[];
    sourceMarkets: PredictorSDK.CanonicalSportsSourceMarket[];
}
