// This file was auto-generated by Fern from our API Definition.

export interface CanonicalSportsSubject {
    /** Canonical subject kind, such as `participant` or `player`. */
    type: string;
    /** Stable subject key within the canonical sports namespace. */
    key: string;
    /** Human-readable subject name. */
    name?: string;
    /** Canonical team key when the subject is a player. */
    team?: string;
}
