// This file was auto-generated by Fern from our API Definition.

export interface CanonicalSportsSourceOutcome {
    /** Canonical outcome this source-native selection represents. */
    canonicalOutcomeKey: string;
    label?: string;
    /** Exact provider-native outcome/token identifier when available. SX Bet exposes one market hash and two named positions rather than separate outcome tokens, so its source-local selection reference is `<market_hash>:1` or `<market_hash>:2`. This field is never a universal cross-provider outcome ID. */
    outcomeId?: string;
    /** Optional source-native side such as `yes` or `no`. */
    side?: string;
}
