// This file was auto-generated by Fern from our API Definition.

/**
 * One outcome of a canonical submarket. A moneyline lists the away team first, a spread `cover` before `not_cover`, and a total, team total or player prop `over` before `under`.
 */
export interface CanonicalSportsOutcome {
    /** What the outcome pays on: `winner:<participant key>` on a moneyline, `cover:<subject>` and `not_cover:<subject>` on a spread (the subject is the side giving points), and `over` and `under` on a total, a team total (the subject's own points) or a player prop. Each source outcome's `canonical_outcome_key` is one of these. */
    key: string;
    label: string;
    type: string;
    side: string;
}
