// This file was auto-generated by Fern from our API Definition.

/** Player props only. `equivalent` requires a complete reviewed profile for every source contract; `different` means at least one known payout-rule difference, even if other rules are unknown; `unverified` means equivalence has not been established and no known difference was found. Absence on game lines makes no claim about their full settlement equivalence. */
export const CanonicalSportsSubmarketSettlementEquivalence = {
    Equivalent: "equivalent",
    Different: "different",
    Unverified: "unverified",
} as const;
export type CanonicalSportsSubmarketSettlementEquivalence =
    (typeof CanonicalSportsSubmarketSettlementEquivalence)[keyof typeof CanonicalSportsSubmarketSettlementEquivalence];
