// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../index.js";

export interface CanonicalSportsEvent {
    /** Stable canonical event key. */
    eventId: string;
    sport?: string;
    league?: string;
    title: string;
    participants?: PredictorSDK.CanonicalSportsParticipant[];
    submarkets: PredictorSDK.CanonicalSportsSubmarket[];
}
