// This file was auto-generated by Fern from our API Definition.

export interface CanonicalSportsRules {
    /** Overtime treatment the submarket's key carries: `incl_ot` (the default) or `reg` on a full-game total or team total, and `incl_ot` on a second-half or fourth-quarter spread, total or team total whose venues' own rules count overtime. A half or quarter means regulation play, so a regulation line publishes no `rules`. Kept for compatibility; the `overtime` row of the submarket's `rule_comparisons` (sent with `include_rules=true`) is each venue's own statement of the same rule and never contradicts it. */
    settlement?: string;
}
