// This file was auto-generated by Fern from our API Definition.

export const CanonicalSportsSourceMarketProvider = {
    Kalshi: "kalshi",
    Polymarket: "polymarket",
    Predict: "predict",
    Sxbet: "sxbet",
    AlphaArcade: "alpha-arcade",
    Prophetx: "prophetx",
    Pred: "pred",
    Limitless: "limitless",
} as const;
export type CanonicalSportsSourceMarketProvider =
    (typeof CanonicalSportsSourceMarketProvider)[keyof typeof CanonicalSportsSourceMarketProvider];
