// This file was auto-generated by Fern from our API Definition.

/** Whether the venues in this submarket settle it the same way, across the rules in `rule_comparisons`. Always present on moneyline, spread, total, team total and player prop submarkets, whether or not `include_rules` asked for the rows behind it. `equivalent` means every rule is known for every venue and agrees; `different` means at least one known difference, even if other rules are unknown; `unverified` means no difference was found but a rule is unknown for at least one venue, so equivalence has not been established. A player prop is `equivalent` only with a complete reviewed profile for every source contract. A game line is compared on three rules, `tie`, `overtime` and `push`, and the comparison never changes which venues are paired: it is the evidence a consumer needs to decide whether a pairing is a hedge. In practice a game line differs on a tie only in a league that can end a game level, which today is the NFL (about 0.3% of games). */
export const CanonicalSportsSubmarketSettlementEquivalence = {
    Equivalent: "equivalent",
    Different: "different",
    Unverified: "unverified",
} as const;
export type CanonicalSportsSubmarketSettlementEquivalence =
    (typeof CanonicalSportsSubmarketSettlementEquivalence)[keyof typeof CanonicalSportsSubmarketSettlementEquivalence];
