// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../index.js";

export interface CanonicalSportsEvent {
    /** Stable canonical event key. */
    eventId: string;
    /** Canonical sport slug. `basketball`, `hockey`, `baseball`, or `football` today. */
    sport?: string;
    /** Canonical league slug. Cross-platform matching covers `nba`, `wnba`, `nhl`, `mlb`, and `nfl` today. The value is the first segment of `event_id`, so `nba-okc-sas-2026-10-20` is an NBA game. Treat this as an open set — leagues are added without a breaking change. */
    league?: string;
    title: string;
    participants?: PredictorSDK.CanonicalSportsParticipant[];
    submarkets: PredictorSDK.CanonicalSportsSubmarket[];
}
