// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../index.js";

export interface CanonicalSportsSourceMarket {
    provider: PredictorSDK.CanonicalSportsSourceMarketProvider;
    /** Exact provider-native market identifier. */
    marketId: string;
    marketName?: string;
    marketSlug?: string;
    outcomes: PredictorSDK.CanonicalSportsSourceOutcome[];
}
