// This file was auto-generated by Fern from our API Definition.

export interface CanonicalSportsSourceOutcome {
    /** Canonical outcome this source-native selection represents: read the team or side it pays on from here, not from `label`. */
    canonicalOutcomeKey: string;
    /** The venue's own name for this selection, as market detail names it: Polymarket's and AlphaArcade's outcome names, SX Bet's and ProphetX's selection names (a spread label carries its sign), and `Yes` or `No` on Kalshi, Pred and Limitless, whose markets are binary questions such as "Atlanta wins". */
    label: string;
    /**
     * Exact provider-native outcome identifier. It is never a universal cross-provider outcome ID.
     *
     * On every provider this is the same value `GET /v1/markets/{market_id}` returns as `outcomes[].outcome_id` for the market named by this row's `market_id`, so the two surfaces join directly.
     *
     * `polymarket`, `predict` and `alpha-arcade` publish a per-outcome token (Polymarket CLOB token id, Predict on-chain id, AlphaArcade CLOB token id), so `source_id={provider}:{outcome_id}` finds this event from the token alone. A token is unique within its provider, not across them: AlphaArcade mirrors Polymarket markets and publishes their CLOB tokens, so the same token can appear under both. Key a token by `provider` as well. `sxbet` and `kalshi` publish no per-outcome token at all, so their references are market-scoped and must be read together with `market_id`: an SX Bet market has one hash and two named positions (`outcomeOne` / `outcomeTwo`), and a Kalshi market is binary (`yes` / `no`). Both are the spelling the venue itself uses to address a side — SX Bet keys its order-book snapshot by `outcomeOne`/`outcomeTwo`, and Kalshi keys its book by `yes`/`no` and reports a trade's `taker_side` the same way. `prophetx` publishes small market-scoped integer outcome ids (e.g. `4`, `5`) that join to the same market's detail row, like SX Bet's positions, and `pred` and `limitless` publish `yes` / `no` like Kalshi. A market-scoped outcome id does not identify a market: `source_id` answers `400` for Kalshi's, Pred's, Limitless's and SX Bet's.
     */
    outcomeId: string;
    /** Optional source-native side such as `yes` or `no`. */
    side?: string;
}
