// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../index.js";

export interface CategoryInfo {
    id: PredictorSDK.MarketCategory;
    /** Human-readable category label. */
    name: string;
    /** Short description of the category's intended scope. */
    description: string;
}
