// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../index.js";

export interface CryptoPricesResponse {
    prices: PredictorSDK.CryptoPriceItem[];
    /** Base64-encoded cursor for fetching the next page. Absent when there are no more results. */
    paginationKey?: string;
    /** Number of prices in this response page. Omitted on empty responses for unknown symbols. */
    total?: number;
}
