// This file was auto-generated by Fern from our API Definition.

export interface CryptoPriceItem {
    /** Trading pair in lowercase (e.g. `btcusdt`). */
    symbol: string;
    /** Close price for the 1-second interval. */
    value: number;
    /** Unix timestamp in milliseconds for the start of the 1-second interval. */
    timestamp: number;
}
