// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../index.js";

export interface CryptoPricesResponse {
    /** One page of prices, newest first, one per second. A single item when no time range was sent; `[]` for an unknown symbol. */
    data: PredictorSDK.CryptoPriceItem[];
    /** Pagination metadata for the current page. `total` is always `null` on this route, and `next_cursor` goes back as `cursor`. */
    pagination: PredictorSDK.PaginationBlock;
}
