// This file was auto-generated by Fern from our API Definition.

/**
 * One problem with one parameter value.
 */
export interface ErrorParamProblem {
    param: string;
    /** The value as sent, truncated if long; empty for an empty value. */
    value: string;
    message: string;
}
