// This file was auto-generated by Fern from our API Definition.

export interface ErrorResponse {
    error: string;
    /** Additional detail about the error. May be present, including on some validation errors. */
    message?: string;
    statusCode: number;
}
