// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../index.js";

/**
 * The body of every error this API returns. Branch on `code`, which is stable; show `message`, which is written for people and may change. A `409` adds `candidates` (see `AmbiguousIdentifierError`) and a `402` adds the billing members of `PaymentRequiredError`.
 */
export interface ErrorResponse {
    /** Stable machine-readable reason. New codes may be added; a code is never renamed or reused. `400`: `unknown_parameter` (the endpoint does not read that query parameter), `invalid_parameter` (a value is malformed, empty, out of range, sent more than once, or contradicts another parameter), `missing_parameter`, `invalid_cursor` (a `cursor` that is malformed, stale, or from another endpoint or filter set: start again without it), `invalid_identifier` (a `market_id` or `event_id` that cannot exist on the provider it resolves to, or whose `{provider}:` prefix names no provider), `upstream_rejected` (the venue rejected the request). `401`: `missing_api_key`, `invalid_api_key`. `402`: `payment_required`. `403`: `forbidden`. `404`: `route_not_found` (no route matches the path), `market_not_found`, `event_not_found`, `profile_not_found`. `405`: `method_not_allowed`. `409`: `ambiguous_identifier`. `429`: `rate_limited` (the per-minute limit; honour `Retry-After`), `usage_limit_exceeded` (an allowance that does not refill within the minute), `upstream_rate_limited` (the venue's limit). `502`: `upstream_unavailable`. `503`: `service_unavailable`. */
    code: string;
    /** What went wrong and how to fix it, for people. It quotes the offending value where there is one. */
    message: string;
    /** The HTTP status code, repeated for logs that keep only the body. */
    statusCode: number;
    /** The query or path parameter the error concerns, when there is one (`provider`, `source_id`, `market_id`, …). */
    param?: string;
    /** Every problem, when a request has more than one: a lookup batch with several bad identifiers, or several malformed parameters. `message` describes the first; each entry here names its own parameter and value. */
    errors?: PredictorSDK.ErrorParamProblem[];
}
