// This file was auto-generated by Fern from our API Definition.

export interface EventFanout {
    /** Sibling event tickers the server attempted to fetch alongside the primary event. Determined by the Kalshi sibling registry for the primary event's series. */
    siblingsAttempted: string[];
    /** Sibling event tickers that returned successfully and contributed markets to the merged response. */
    siblingsReturned: string[];
    /** Sibling event tickers that did not exist upstream (404) or errored. The primary event still returned 200 — these are reported for observability, not as request failures. */
    siblingsMissing: string[];
}
