// This file was auto-generated by Fern from our API Definition.

/** The provider the event_id was resolved against, either inferred from the ID format or supplied via `?provider=`. It is the value to send as `?provider=` to `GET /v1/markets/{market_id}` with a nested market's `market_id` (it was named `platform` until 2026-10-09). */
export const EventResponseProvider = {
    Kalshi: "kalshi",
    Polymarket: "polymarket",
    Predict: "predict",
    Sxbet: "sxbet",
    Hyperliquid: "hyperliquid",
    AlphaArcade: "alpha-arcade",
    Prophetx: "prophetx",
    Limitless: "limitless",
    Pred: "pred",
} as const;
export type EventResponseProvider = (typeof EventResponseProvider)[keyof typeof EventResponseProvider];
