// This file was auto-generated by Fern from our API Definition.

export interface EventMarket {
    /** Platform-native market identifier. Kalshi ticker (`KXMLBGAME-26AUG272145AZSF-AZ`), Polymarket numeric market id, SX Bet `marketHash`, or Predict market id. */
    marketId: string;
    /** Human-readable market title/question. */
    title: string;
}
