// This file was auto-generated by Fern from our API Definition.

/** The platform the event_id was resolved against, either inferred from the ID format or supplied via `?platform=`. */
export const EventResponsePlatform = {
    Kalshi: "kalshi",
    Polymarket: "polymarket",
    Predict: "predict",
    Sxbet: "sxbet",
} as const;
export type EventResponsePlatform = (typeof EventResponsePlatform)[keyof typeof EventResponsePlatform];
