// This file was auto-generated by Fern from our API Definition.

export interface EventMarket {
    /** Platform-native market identifier. Kalshi ticker (`KXMLBGAME-26AUG272145AZSF-AZ`), Polymarket numeric market id, SX Bet `marketHash`, Predict market id, Hyperliquid outcome id, AlphaArcade market ULID, or ProphetX `<event_id>:<market_id>`. */
    marketId: string;
    /** Human-readable market title/question. */
    title: string;
}
