// This file was auto-generated by Fern from our API Definition.

export const GetMarketsRequestProvider = {
    Kalshi: "kalshi",
    Polymarket: "polymarket",
    Predict: "predict",
    Sxbet: "sxbet",
    Hyperliquid: "hyperliquid",
    AlphaArcade: "alpha-arcade",
} as const;
export type GetMarketsRequestProvider = (typeof GetMarketsRequestProvider)[keyof typeof GetMarketsRequestProvider];
