// This file was auto-generated by Fern from our API Definition.

export const GetMarketRequestProvider = {
    Kalshi: "kalshi",
    Polymarket: "polymarket",
    Predict: "predict",
    Sxbet: "sxbet",
    Hyperliquid: "hyperliquid",
    AlphaArcade: "alpha-arcade",
    Prophetx: "prophetx",
    Limitless: "limitless",
    Pred: "pred",
} as const;
export type GetMarketRequestProvider = (typeof GetMarketRequestProvider)[keyof typeof GetMarketRequestProvider];
