// This file was auto-generated by Fern from our API Definition.

export const GetSportsMatchingMarketsRequestPlayerPropMatch = {
    Strict: "strict",
    SameProp: "same_prop",
} as const;
export type GetSportsMatchingMarketsRequestPlayerPropMatch =
    (typeof GetSportsMatchingMarketsRequestPlayerPropMatch)[keyof typeof GetSportsMatchingMarketsRequestPlayerPropMatch];
