// This file was auto-generated by Fern from our API Definition.

export const GetSportsMatchingMarketsRequestLeague = {
    Nba: "nba",
    Wnba: "wnba",
    Nfl: "nfl",
    Mlb: "mlb",
    Nhl: "nhl",
} as const;
export type GetSportsMatchingMarketsRequestLeague =
    (typeof GetSportsMatchingMarketsRequestLeague)[keyof typeof GetSportsMatchingMarketsRequestLeague];
