// This file was auto-generated by Fern from our API Definition.

export const LookupSportsMatchingMarketsRequestPlayerPropMatch = {
    Strict: "strict",
    SameProp: "same_prop",
} as const;
export type LookupSportsMatchingMarketsRequestPlayerPropMatch =
    (typeof LookupSportsMatchingMarketsRequestPlayerPropMatch)[keyof typeof LookupSportsMatchingMarketsRequestPlayerPropMatch];
