// This file was auto-generated by Fern from our API Definition.

/** Self-describing unit declaration for all price fields. Single canonical scale today; new values would be added alongside (never replacing) this one. */
export const MarketDetailPricingScale = {
    Probability01: "probability_0_1",
} as const;
export type MarketDetailPricingScale = (typeof MarketDetailPricingScale)[keyof typeof MarketDetailPricingScale];
