// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../index.js";

export interface MarketsListResponse {
    /** Array of markets for the current page. */
    data: PredictorSDK.UnifiedMarket[];
    /** Pagination metadata for the current page. */
    pagination: PredictorSDK.PaginationBlock;
}
