// This file was auto-generated by Fern from our API Definition.

/**
 * The price term of the per-share fee.
 *
 * `quadratic` — `rate × (price × (1 − price)) ^ exponent`. Kalshi (`roundup(0.07 × C × P × (1−P))`, exponent 1 by published formula), Polymarket (`fee = C × feeRate × p × (1 − p)`, exponent read per market), AlphaArcade (`feeBase × quantity × price × (1 − price)`).
 *
 * `min_price` — `rate × min(price, 1 − price)`. Predict (`Base Fee % × min(Price, 1 − Price) × Shares`). A TENT, not a parabola: the effective rate on notional is flat at `rate` for every price at or below 0.5 and only declines above it. Do not collapse this into `quadratic`; it would overstate the fee at every price below 0.5.
 *
 * `notional` — `rate × price`, i.e. a flat fraction of traded notional with no price curve at all.
 *
 * `none` — zero, asserted.
 */
export const MarketDetailFeeLegModel = {
    Quadratic: "quadratic",
    MinPrice: "min_price",
    Notional: "notional",
    None: "none",
} as const;
export type MarketDetailFeeLegModel = (typeof MarketDetailFeeLegModel)[keyof typeof MarketDetailFeeLegModel];
