// This file was auto-generated by Fern from our API Definition.

/** Where the parameters came from, so a latency-sensitive consumer knows which platforms cost extra hops. `market_record` — embedded in the same market record the identity fetch already returned (Polymarket `feeSchedule`, Predict `feeRateBps`, AlphaArcade `feeBasePercent`); zero extra fetches. `series_record` — the parameters live on parent records and cost up to three small, TTL-cached hops (Kalshi: the event record for its series ticker and any fee override in force, the series for the base `fee_type`/`fee_multiplier` that override supersedes, then the event's pending fee changes for `scheduled_change`). `venue_schedule` — the venue exposes no per-market parameter and the answer comes from its published schedule (SX Bet, Hyperliquid). */
export const MarketDetailTradingFeesSource = {
    MarketRecord: "market_record",
    SeriesRecord: "series_record",
    VenueSchedule: "venue_schedule",
} as const;
export type MarketDetailTradingFeesSource =
    (typeof MarketDetailTradingFeesSource)[keyof typeof MarketDetailTradingFeesSource];
