// This file was auto-generated by Fern from our API Definition.

/** Where the quotes came from. `market_record` — embedded in the same record as the identity fetch: Kalshi, Polymarket and Predict, and the group views of Limitless and Pred, which read no order book. `orderbook` — the platform's order book, in a bounded second fetch where it is a separate route: SX Bet (`/orderbook-v3/snapshot`), Hyperliquid (`l2Book`), AlphaArcade, Limitless, Pred and ProphetX. A failed book read keeps `orderbook` and reports `availability: unavailable` or the record's marks. */
export const MarketDetailPricingSource = {
    MarketRecord: "market_record",
    Orderbook: "orderbook",
} as const;
export type MarketDetailPricingSource = (typeof MarketDetailPricingSource)[keyof typeof MarketDetailPricingSource];
