// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../index.js";

/**
 * The trading fee the PREDICTION MARKET charges on a trade in this market — the venue's own published parameters, normalized. This has nothing to do with PredictorSDK's subscription pricing.
 *
 * Always present on the response. Every published model across the nine platforms is a per-share fee times the traded share count, and only the price term differs, so `taker.model` plus its parameters expresses each venue exactly rather than approximating any of them — except Limitless, whose taker curve is published as table rows with no closed form: its descriptor reports `partial` with a null taker leg instead of inventing a number. (A Limitless market with fees disabled reports `published` with both legs zero — an asserted free, never an unknown. A Pred market whose record omits `fee_rate_bps` reports `partial` for the same reason: the venue's own integration note says absent fee configuration must be confirmed, not assumed fee-free.) Compute the fee yourself:
 *
 * `fee = shares × f(price)`, then apply `rounding`, where `f` is
 *
 * - `quadratic`: `rate × (price × (1 − price)) ^ exponent`
 * - `min_price`: `rate × min(price, 1 − price)`
 * - `notional`: `rate × price`
 * - `none`: `0`
 *
 * The effective rate on notional — what you actually compare across venues — is `f(price) / price`. For `quadratic` at `exponent: 1` that reduces to `rate × (1 − price)`, which is why no single basis-point figure can express any of these venues: at `rate: 0.07` the effective cost runs from 693 bps at a price of 0.01 down to 7 bps at 0.99.
 *
 * `availability` and the legs are on separate axes on purpose: availability says what is KNOWN, the legs say what is CHARGED. A fee-free market is `availability: published` with `model: "none"` and `rate: 0` — an asserted zero, distinguishable from `unpublished` (the venue publishes nothing) and from `account_specific` (rates exist but are per-account).
 *
 * OUT OF SCOPE and therefore not modeled as fields, though each is real and moves the number: rebates (Polymarket's maker-rebate and taker-rebate programs), per-account discounts (Predict's 10% invite discount), volume/staking tiers and the market deployer's own fee, its `deployerFeeScale` (Hyperliquid), and third-party pass-through (Kalshi FCM customers, Polymarket builder fees). The parameters here are the venue's PUBLISHED base for this market; a specific account may pay less.
 */
export interface MarketDetailTradingFees {
    /** `published` — the full parameter set for this market is known. `partial` — fees may be charged here but a parameter is missing or uninterpretable upstream; the legs carry what is known and null the rest, never a guess. It also covers the case where the parameters in force are known but the venue's pending-change list was unreadable, so an omitted `scheduled_change` means "unknown" rather than "none". `account_specific` — rates exist but are set per trading account and require your own venue credentials (SX Bet's `GET /user/fees-v3`, Hyperliquid's `POST /info {"type":"userFees"}`). `unpublished` — the venue publishes no fee model for this market at all. `unavailable` — our own bounded parameter fetch failed or timed out; identity and pricing are still served. Same contract as `pricing.availability`. */
    availability: PredictorSDK.MarketDetailTradingFeesAvailability;
    /**
     * When PredictorSDK READ these parameter values — an observation timestamp, not an upstream stamp.
     *
     * Named `observed_at` rather than `as_of` deliberately: `pricing.as_of` is the provider record's own last-update time, which is a different thing, and reusing the name for a differently-defined timestamp would bake that confusion into a second field. Null when nothing is read at request time (`source: venue_schedule`) or when nothing could be read (`availability: unavailable`).
     */
    observedAt: Date | null;
    /** Where the parameters came from, so a latency-sensitive consumer knows which platforms cost extra hops. `market_record` — embedded in the same market record the identity fetch already returned (Polymarket `feeSchedule`, Predict `feeRateBps`, AlphaArcade `feeBasePercent`); zero extra fetches. `series_record` — the parameters live on parent records and cost up to three small, TTL-cached hops (Kalshi: the event record for its series ticker and any fee override in force, the series for the base `fee_type`/`fee_multiplier` that override supersedes, then the event's pending fee changes for `scheduled_change`). `venue_schedule` — the venue exposes no per-market parameter and the answer comes from its published schedule (SX Bet, Hyperliquid). */
    source: PredictorSDK.MarketDetailTradingFeesSource;
    /**
     * What the fee is assessed on. `fill` — assessed when the order fills, from the traded share count and the fill price. `settlement_profit` — assessed at settlement, on profit (total return − stake), and only on a position that WON; a loss or a void is never charged. `close_or_settlement` — assessed when a position is closed or settles, and never when one is opened.
     *
     * Read this before comparing rates across venues. SX Bet charges on winning profit at settlement, so its fee is an expected-value haircut rather than an entry cost — a consumer that models it as a percentage of notional is wrong about the shape before it is wrong about the rate. The reported basis is the one that applies to trading: SX Bet's four payout fees. Its separate `refundFee` is charged at fill time on the capital-efficiency refund rather than on profit, and is out of scope here along with its rates.
     *
     * Hyperliquid's outcome markets are `close_or_settlement`: its fee page says outcome trading "only charges fees when closing or settling, not when opening outcome positions", so a buy that opens a position costs nothing and outcome trading has no maker rebates. The rate is still the account's own (`account_specific`, `rate: null`), and a market's deployer can add a fee on top through the `deployerFeeScale` in Hyperliquid's `outcomeMeta` (`1.0` on outcomes from the `out` and `skew` deployers; trade.xyz documents `0`, which adds none, for its own).
     */
    chargeBasis: PredictorSDK.MarketDetailTradingFeesChargeBasis | null;
    /** The taker leg: the fee on the incoming order that fills a resting one. Always present, and **`null` (never omitted) when no model can be stated for this side**. `availability` says when. `published`: never null. `partial`: null where the venue does not let us state the leg, which today is Limitless's taker (a curve with no closed form) and both legs of a market whose record omits its fee parameters (or, on Kalshi, names a fee type we do not model). `account_specific`: null for SX Bet, whose rates are set per account (Hyperliquid returns the leg with a null `rate` instead). `unavailable`: always null, because the parameters could not be read or the venue (ProphetX) publishes none. `unpublished`: always null. So `taker.rate` can be read without a null check once `availability` is `published`. */
    taker: PredictorSDK.MarketDetailFeeLeg | null;
    /** The maker leg: the fee on the resting order a taker fills. Always present, and **`null` (never omitted) when no model can be stated for this side**. `availability` says when. `published`: never null. `partial`: null for a Polymarket market whose record does not say that only takers pay, and for both legs of a market whose record omits its fee parameters (or, on Kalshi, names a fee type we do not model). `account_specific`: null for SX Bet, whose rates are set per account (Hyperliquid returns the leg with a null `rate` instead). `unavailable`: always null, because the parameters could not be read or the venue (ProphetX) publishes none. `unpublished`: always null. So `maker.rate` can be read without a null check once `availability` is `published`. */
    maker: PredictorSDK.MarketDetailFeeLeg | null;
    scheduledChange?: PredictorSDK.MarketDetailScheduledFeeChange;
}
