// This file was auto-generated by Fern from our API Definition.

/**
 * What the fee is assessed on. `fill` — assessed when the order fills, from the traded share count and the fill price. `settlement_profit` — assessed at settlement, on profit (total return − stake), and only on a position that WON; a loss or a void is never charged. `close_or_settlement` — assessed when a position is closed or settles, and never when one is opened.
 *
 * Read this before comparing rates across venues. SX Bet charges on winning profit at settlement, so its fee is an expected-value haircut rather than an entry cost — a consumer that models it as a percentage of notional is wrong about the shape before it is wrong about the rate. The reported basis is the one that applies to trading: SX Bet's four payout fees. Its separate `refundFee` is charged at fill time on the capital-efficiency refund rather than on profit, and is out of scope here along with its rates.
 *
 * Hyperliquid's outcome markets are `close_or_settlement`: its fee page says outcome trading "only charges fees when closing or settling, not when opening outcome positions", so a buy that opens a position costs nothing and outcome trading has no maker rebates. The rate is still the account's own (`account_specific`, `rate: null`), and a market's deployer can add a fee on top through the `deployerFeeScale` in Hyperliquid's `outcomeMeta` (`1.0` on outcomes from the `out` and `skew` deployers; trade.xyz documents `0`, which adds none, for its own).
 */
export const MarketDetailTradingFeesChargeBasis = {
    Fill: "fill",
    SettlementProfit: "settlement_profit",
    CloseOrSettlement: "close_or_settlement",
} as const;
export type MarketDetailTradingFeesChargeBasis =
    (typeof MarketDetailTradingFeesChargeBasis)[keyof typeof MarketDetailTradingFeesChargeBasis];
