// This file was auto-generated by Fern from our API Definition.

/** Where the quotes came from. `market_record` — embedded in the same single-market record as the identity fetch (Kalshi, Polymarket, Predict). `orderbook` — required one bounded second fetch against the platform's order-book surface (SX Bet `/orderbook-v3/snapshot`, Hyperliquid `l2Book`). */
export const MarketDetailPricingSource = {
    MarketRecord: "market_record",
    Orderbook: "orderbook",
} as const;
export type MarketDetailPricingSource = (typeof MarketDetailPricingSource)[keyof typeof MarketDetailPricingSource];
