// This file was auto-generated by Fern from our API Definition.

/** `live` — every outcome carries a price. `partial` — some but not all outcomes priced. `no_quotes` — the pricing fetch succeeded but the book is empty (SX Bet or Hyperliquid with no resting orders; Kalshi provisional/multivariate markets whose quotes are empty-book placeholders). `unavailable` — the pricing enrichment fetch failed or timed out (SX Bet/Hyperliquid); identity fields are still served. */
export const MarketDetailPricingAvailability = {
    Live: "live",
    Partial: "partial",
    NoQuotes: "no_quotes",
    Unavailable: "unavailable",
} as const;
export type MarketDetailPricingAvailability =
    (typeof MarketDetailPricingAvailability)[keyof typeof MarketDetailPricingAvailability];
