// This file was auto-generated by Fern from our API Definition.

/**
 * What the fee is assessed on. `fill` — assessed when the order fills, from the traded share count and the fill price. `settlement_profit` — assessed at settlement, on profit (total return − stake), and only on a position that WON; a loss or a void is never charged.
 *
 * Read this before comparing rates across venues. SX Bet charges on winning profit at settlement, so its fee is an expected-value haircut rather than an entry cost — a consumer that models it as a percentage of notional is wrong about the shape before it is wrong about the rate. The reported basis is the one that applies to trading: SX Bet's four payout fees. Its separate `refundFee` is charged at fill time on the capital-efficiency refund rather than on profit, and is out of scope here along with its rates.
 */
export const MarketDetailTradingFeesChargeBasis = {
    Fill: "fill",
    SettlementProfit: "settlement_profit",
} as const;
export type MarketDetailTradingFeesChargeBasis =
    (typeof MarketDetailTradingFeesChargeBasis)[keyof typeof MarketDetailTradingFeesChargeBasis];
