// This file was auto-generated by Fern from our API Definition.

/** PredictorSDK-normalized top-level category. This is intentionally broad and stable across providers; provider-native tags are not exposed as canonical categories. */
export const MarketCategory = {
    Sports: "sports",
    Politics: "politics",
    Crypto: "crypto",
    Finance: "finance",
    Economics: "economics",
    Weather: "weather",
    Culture: "culture",
    Technology: "technology",
    Entertainment: "entertainment",
    Other: "other",
    Unknown: "unknown",
} as const;
export type MarketCategory = (typeof MarketCategory)[keyof typeof MarketCategory];
