// This file was auto-generated by Fern from our API Definition.

/** Normalized lifecycle status. Mapping per platform: Kalshi `active` → open · `closed`/`determined` → closed · `settled`/`finalized` → settled. Polymarket `archived` → settled · `closed && !archived` → closed · otherwise → open. Predict `tradingStatus=OPEN` → open · `CLOSED && !RESOLVED` → closed · `status=RESOLVED` → settled. SX Bet `ACTIVE` → open · otherwise closed. Unknown upstream values default to closed. */
export const MarketDetailResponseStatus = {
    Open: "open",
    Closed: "closed",
    Settled: "settled",
} as const;
export type MarketDetailResponseStatus = (typeof MarketDetailResponseStatus)[keyof typeof MarketDetailResponseStatus];
