// This file was auto-generated by Fern from our API Definition.

/** Prediction market provider the market_id resolved against. */
export const MarketDetailResponseProvider = {
    Kalshi: "kalshi",
    Polymarket: "polymarket",
    Predict: "predict",
    Sxbet: "sxbet",
} as const;
export type MarketDetailResponseProvider =
    (typeof MarketDetailResponseProvider)[keyof typeof MarketDetailResponseProvider];
