// This file was auto-generated by Fern from our API Definition.

/** `published` — the full parameter set for this market is known. `partial` — fees may be charged here but a parameter is missing or uninterpretable upstream; the legs carry what is known and null the rest, never a guess. It also covers the case where the parameters in force are known but the venue's pending-change list was unreadable, so an omitted `scheduled_change` means "unknown" rather than "none". `account_specific` — rates exist but are set per trading account and require your own venue credentials (SX Bet's `GET /user/fees-v3`, Hyperliquid's `POST /info {"type":"userFees"}`). `unpublished` — the venue publishes no fee model for this market at all. `unavailable` — our own bounded parameter fetch failed or timed out; identity and pricing are still served. Same contract as `pricing.availability`. */
export const MarketDetailTradingFeesAvailability = {
    Published: "published",
    Partial: "partial",
    AccountSpecific: "account_specific",
    Unpublished: "unpublished",
    Unavailable: "unavailable",
} as const;
export type MarketDetailTradingFeesAvailability =
    (typeof MarketDetailTradingFeesAvailability)[keyof typeof MarketDetailTradingFeesAvailability];
