// This file was auto-generated by Fern from our API Definition.

export interface PaginationBlock {
    /** Number of items requested per page (echoes the `limit` query param). */
    limit: number;
    /** Total matching items across all pages. */
    total: number;
    /** Whether additional pages exist beyond this one. */
    hasMore: boolean;
    /** Opaque cursor for fetching the next page. Pass back via the `cursor` query parameter. Omitted when `has_more` is `false`. Clients must preserve the same filter set when re-using a cursor — mismatches return `400`. */
    nextCursor?: string;
}
