// This file was auto-generated by Fern from our API Definition.

/** Recommended client action for this 402. */
export const PaymentRequiredErrorAction = {
    UpgradePlan: "upgrade_plan",
    ResolvePayment: "resolve_payment",
} as const;
export type PaymentRequiredErrorAction = (typeof PaymentRequiredErrorAction)[keyof typeof PaymentRequiredErrorAction];
