// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../index.js";

/**
 * Error body returned with HTTP 402. The `action` discriminator lets clients route to the correct recovery flow: `upgrade_plan` means the caller is on a lower tier than the endpoint requires, or the Free monthly allowance is exhausted; `resolve_payment` means the caller had a paid subscription that entered a payment-recovery state (past_due/unpaid/paused/incomplete) and the backend has already downgraded them to Free — the fix is in the billing portal, not a new purchase. `required_tier` / `current_tier` are always populated; `included_requests_per_month` and `current_period_requests` are only set when a Free caller hits the monthly allowance.
 */
export interface PaymentRequiredErrorBody {
    /** Always `payment_required`. */
    code: string;
    /** What the caller needs to do, for people. */
    message: string;
    statusCode: number;
    action: PredictorSDK.PaymentRequiredErrorAction;
    /** Billing tier that would satisfy the gate: `starter`, `pro` or `enterprise`, the `billing_tier` of a plan in `GET /v1/plans` (the Business plan's tier is `enterprise`). */
    requiredTier: string;
    /** Billing tier currently associated with the caller: `free`, `starter`, `pro` or `enterprise`. */
    currentTier: string;
    /** Monthly Free-tier allowance. Present only when the 402 is caused by the Free cap. */
    includedRequestsPerMonth?: number;
    /** Requests the Free caller has made in the current calendar month. Present only when the 402 is caused by the Free cap. */
    currentPeriodRequests?: number;
}
