// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../index.js";

/**
 * Error body returned with HTTP 402. The `action` discriminator lets clients route to the correct recovery flow: `upgrade_plan` means the caller is on a lower tier than the endpoint requires, or the Free monthly allowance is exhausted; `resolve_payment` means the caller had a paid subscription that entered a payment-recovery state (past_due/unpaid/paused/incomplete) and the backend has already downgraded them to Free — the fix is in the billing portal, not a new purchase. `required_tier` / `current_tier` are always populated; `included_requests_per_month` and `current_period_requests` are only set when a Free caller hits the monthly allowance.
 */
export interface PaymentRequiredErrorBody {
    error: string;
    /** Additional detail about the error. */
    message?: string;
    statusCode: number;
    /** Recommended client action for this 402. */
    action: PredictorSDK.PaymentRequiredErrorAction;
    /** Billing tier that would satisfy the gate (e.g. `starter`, `pro`, `business`, `enterprise`). */
    requiredTier: string;
    /** Billing tier currently associated with the caller. */
    currentTier: string;
    /** Monthly Free-tier allowance. Present only when the 402 is caused by the Free cap. */
    includedRequestsPerMonth?: number;
    /** Requests the Free caller has made in the current calendar month. Present only when the 402 is caused by the Free cap. */
    currentPeriodRequests?: number;
}
