// This file was auto-generated by Fern from our API Definition.

/**
 * Public plan metadata. Stripe price IDs and legacy provisioning IDs are intentionally absent.
 */
export interface Plan {
    /** Stable public plan key. */
    key: string;
    name: string;
    /** Runtime entitlement tier; empty for a manually provisioned contact-sales plan. */
    billingTier: string;
    trialDays: number;
    tagline: string;
    /** Monthly display price in US cents; zero for free or contact-sales plans. */
    monthlyPriceCents: number;
    includedRequestsPerMonth: number;
    overageCentsPer1K: number;
    rateLimitPerMin: number;
    maxKeys: number;
    features: string[];
    ctaLabel: string;
    highlighted: boolean;
    contactSales: boolean;
}
