// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../index.js";

export interface PlatformMarket {
    platform: PredictorSDK.PlatformMarketPlatform;
    /** Kalshi event ticker. Present when platform is KALSHI. */
    eventTicker?: string;
    /** Kalshi market tickers. Present when platform is KALSHI. */
    marketTickers?: string[];
    /** Polymarket market slug. Present when platform is POLYMARKET. */
    marketSlug?: string;
    /** Polymarket token IDs. Present when platform is POLYMARKET. */
    tokenIds?: string[];
    /** Source market ID. Present for platforms other than Kalshi and Polymarket. */
    marketId?: string;
    /** Source outcome IDs. Present for platforms that use outcome IDs. */
    outcomeIds?: string[];
}
