// This file was auto-generated by Fern from our API Definition.

export const PlatformMarketPlatform = {
    Kalshi: "KALSHI",
    Polymarket: "POLYMARKET",
    Predict: "PREDICT",
    Sxbet: "SXBET",
} as const;
export type PlatformMarketPlatform = (typeof PlatformMarketPlatform)[keyof typeof PlatformMarketPlatform];
