// This file was auto-generated by Fern from our API Definition.

export const PlayerPropRuleComparisonRule = {
    NonParticipation: "non_participation",
    Overtime: "overtime",
    StatDefinition: "stat_definition",
    Threshold: "threshold",
    StatCorrections: "stat_corrections",
    Postponement: "postponement",
    Cancellation: "cancellation",
    Interruption: "interruption",
    ResolutionSource: "resolution_source",
} as const;
export type PlayerPropRuleComparisonRule =
    (typeof PlayerPropRuleComparisonRule)[keyof typeof PlayerPropRuleComparisonRule];
