// This file was auto-generated by Fern from our API Definition.

/** Known differences take precedence over unknown source values. */
export const PlayerPropRuleComparisonComparison = {
    Equivalent: "equivalent",
    Different: "different",
    Unverified: "unverified",
} as const;
export type PlayerPropRuleComparisonComparison =
    (typeof PlayerPropRuleComparisonComparison)[keyof typeof PlayerPropRuleComparisonComparison];
