// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../index.js";

export interface PlayerPropRuleComparison {
    rule: PredictorSDK.PlayerPropRuleComparisonRule;
    /** Human-readable name of the rule dimension. */
    label: string;
    /** Known differences take precedence over unknown source values. */
    comparison: PredictorSDK.PlayerPropRuleComparisonComparison;
    sourceValues: PredictorSDK.PlayerPropRuleSourceValue[];
}
