// This file was auto-generated by Fern from our API Definition.

/** `overtime` is shared by props and game lines. `tie` and `push` appear on game lines only: `tie` is what the venue does when the game or period ends level, and `push` what it does when the result lands exactly on a whole-number line. */
export const PlayerPropRuleComparisonRule = {
    NonParticipation: "non_participation",
    Overtime: "overtime",
    StatDefinition: "stat_definition",
    Threshold: "threshold",
    StatCorrections: "stat_corrections",
    Postponement: "postponement",
    Cancellation: "cancellation",
    Interruption: "interruption",
    ResolutionSource: "resolution_source",
    Tie: "tie",
    Push: "push",
} as const;
export type PlayerPropRuleComparisonRule =
    (typeof PlayerPropRuleComparisonRule)[keyof typeof PlayerPropRuleComparisonRule];
