// This file was auto-generated by Fern from our API Definition.

export interface PlayerPropRuleSourceValue {
    /** Lowercase provider slug matching a source_markets entry. */
    provider: string;
    /** Exact native market ID matching a source_markets entry. */
    marketId: string;
    /** Machine-readable observed rule value, or `unknown`. Values are extensible; clients must tolerate unfamiliar values and read description. Never interpret unknown as no restriction. */
    value: string;
    /** Plain-language meaning, including relevant qualifications. */
    description: string;
    /** Source contract containing the observed clause; omitted for unknown rules. */
    evidenceUrl?: string;
}
