// This file was auto-generated by Fern from our API Definition.

export interface PolymarketPosition {
    /** Polymarket condition ID (`0x`-prefixed hex). */
    conditionId: string;
    /** Outcome label held in this position (`Yes`/`No` for binary markets). */
    outcome: string;
    /** Number of outcome shares held. */
    shares: number;
}
