// This file was auto-generated by Fern from our API Definition.

export interface PolymarketPosition {
    /** Polymarket condition ID (`0x`-prefixed hex). */
    conditionId: string;
    /** Outcome label held in this position (`Yes`/`No` for binary markets). */
    outcome: string;
    /** Current number of outcome shares held, not lifetime shares bought. */
    shares: number;
}
