// This file was auto-generated by Fern from our API Definition.

export interface PolymarketWalletResponse {
    /** Polymarket proxy address (lowercased) the profile is keyed on. When the input was a signer EOA, this is the resolved proxy. */
    address: string;
    /** Original signer EOA from the request, when the input was an EOA that resolved to a different proxy. `null` when the input was already a proxy address (no resolution needed) or when no populated profile could be found for the resolved proxy. */
    signer: string | null;
    /** URL of the wallet's profile image, or `null` if unset. */
    profileImage: string | null;
    /** User-chosen display name when set; otherwise the auto-generated pseudonym Polymarket assigns. `null` only when both are missing. */
    displayName: string | null;
}
