// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../index.js";

export interface PolymarketPositionsResponse {
    /** Resolved Polymarket proxy wallet (lowercased). */
    address: string;
    data: PredictorSDK.PolymarketPosition[];
    pagination: PredictorSDK.PaginationBlock;
}
