// This file was auto-generated by Fern from our API Definition.

/**
 * Freshness of the matching snapshot a `GET /v1/matching-markets/sports` response was read from. Matching runs continuously in the background, so an event a response does not contain may be unmatched across venues, or missing from a snapshot that stopped updating. This block tells you whether the snapshot is still updating.
 */
export interface SportsMatchingSnapshot {
    /**
     * When PredictorSDK began the OLDEST venue read behind the matching snapshot this response came from — a conservative freshness floor for every event in that snapshot, in millisecond-precision ISO 8601. Present in list and lookup mode alike, including a lookup that matched nothing, which is when it matters most.
     *
     * **What to expect.** Matching re-reads every venue about every 30 seconds plus the time the read itself takes, and keeps a venue's last good read for at most 10 minutes after that read finished. While matching is healthy this value is therefore never more than about 12 minutes old, and normally under two minutes. Anything older means the snapshot has stopped updating: treat an event the response does not contain as unknown rather than unmatched. The value dates the venue reads the snapshot holds; a venue whose reads keep failing is dropped from it once its last good read is 10 minutes old, so that venue's events can be missing even from a current snapshot.
     *
     * `observed_at` is a PredictorSDK read time, the same meaning it carries on `pricing.observed_at` and on the catalog's `snapshot.observed_at`. It is not when a venue last changed a market, and not a game time. It is the start of the read, never its end, so it can never claim data is newer than it is.
     *
     * Each response reports the snapshot it read. Pages of one cursor traversal can come from successive snapshots, so the value can advance between pages. Events that `include_settled=true` adds from the settled archive have left the current snapshot; they keep the identity they had when they left it, which can be days old, and do not affect this value.
     *
     * `null` when the age is unknown, for example while a snapshot written before this field existed is still being served.
     */
    observedAt: Date | null;
}
