// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../index.js";

export interface SportsMatchingLookupResponse {
    /** The matched events the identifiers found, soonest scheduled start first, each once however many identifiers found it. Present on every response, as `[]` when nothing matched. */
    data: PredictorSDK.CanonicalSportsEvent[];
    /** Every `event_id` and `source_id` sent, under its spelling as sent (whitespace around the provider and ID trimmed), with the canonical events in `data` that hold it. An identifier that found nothing is listed with no events. */
    lookups: Record<string, PredictorSDK.SportsMatchingLookupResult>;
    /** Freshness of the matching snapshot this response was read from. Present even when no identifier matched, which is when it matters most. */
    snapshot: PredictorSDK.SportsMatchingSnapshot;
}
