// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../index.js";

export interface SportsMatchingResponse {
    /** Key-value pairs where each key is the queried identifier (Kalshi event ticker, Polymarket slug, or canonical event ID when no filter is provided) and each value is an array of platform market objects. */
    markets: Record<string, PredictorSDK.PlatformMarket[]>;
}
