// This file was auto-generated by Fern from our API Definition.

/**
 * What one lookup identifier found.
 */
export interface SportsMatchingLookup {
    /** The `event_id`s of the canonical events in `data` that hold the identifier, matched case-insensitively. Usually one; several only when venues reuse an identifier; none when no event in the selected population holds it: the market is matched by no other venue, the game is past-dated (see `include_settled`), its full-game moneyline is unmatched under `include_submarkets=false`, the game's only matches are player props the `player_prop_match` policy excludes (try `same_prop`), or the identifier is unknown. */
    eventIds: string[];
}
