// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../index.js";

export interface SportsMatchingResponse {
    /** Matched events, soonest scheduled start first, each once however many lookup identifiers found it. Present on every response, as `[]` when nothing matched. */
    data: PredictorSDK.CanonicalSportsEvent[];
    /** Lookup mode only: every `event_id` and `source_id` sent, under its spelling as sent (whitespace around the provider and ID trimmed), with the canonical events in `data` that hold it. An identifier that found nothing is listed with no events. Absent in list mode. */
    lookups?: Record<string, PredictorSDK.SportsMatchingLookup>;
    /** Pagination metadata for the current page. Present in list mode (no `event_id` or `source_id`). Absent in lookup mode, since the response is bounded by the identifiers requested. */
    pagination?: PredictorSDK.PaginationBlock;
    /** Freshness of the matching snapshot this response was read from. Present in list and lookup mode alike. Describes the DATA; `pagination` describes the page. */
    snapshot: PredictorSDK.SportsMatchingSnapshot;
}
