// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../index.js";

export interface SportsMatchingListResponse {
    /** One page of matched events, soonest scheduled start first, each once. Present on every response, as `[]` when nothing matched. */
    data: PredictorSDK.CanonicalSportsEvent[];
    /** Pagination metadata for the current page. `total` counts the events that match the request's filters, not every matched event. */
    pagination: PredictorSDK.PaginationBlock;
    /** Freshness of the matching snapshot this response was read from. Describes the DATA; `pagination` describes the page. */
    snapshot: PredictorSDK.SportsMatchingSnapshot;
}
