// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../index.js";

export interface UnifiedMarket {
    /** Composite market identifier in the format `{provider}:{provider_id}` (e.g. `kalshi:KXNBAGAME-26MAR06INDLAL-LAL`). */
    id: string;
    /** Prediction market provider. */
    provider: PredictorSDK.UnifiedMarketProvider;
    /** Human-readable market title/question. */
    title: string;
}
