// This file was auto-generated by Fern from our API Definition.

/** Prediction market provider. */
export const UnifiedMarketProvider = {
    Kalshi: "kalshi",
    Polymarket: "polymarket",
    Predict: "predict",
    Sxbet: "sxbet",
} as const;
export type UnifiedMarketProvider = (typeof UnifiedMarketProvider)[keyof typeof UnifiedMarketProvider];
