// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../index.js";

/**
 * @example
 *     {
 *         eventId: "KXNBAGAME-26OCT20OKCSAS"
 *     }
 */
export interface GetEventRequest {
    /**
     * Provider-native event identifier. Examples per provider: Kalshi event ticker (`KXNBAGAME-26OCT20OKCSAS`), Polymarket event slug (`nfl-pit-ne-2026-09-20`), SX Bet event id (`L19766755`), Predict market id (`1607914`), Hyperliquid question or outcome integer id (requires `?provider=hyperliquid` since integer ids aren't inferred), Pred parent market id (`0x…64hex`, requires `?provider=pred` since the shape collides with SX Bet market hashes). The composite `{provider}:{native_id}` form (e.g. `predict:1607914`) is accepted here too and dispatches without probing.
     *
     * **A bare numeric id or slug is not unique across providers.** Polymarket and Predict both use these shapes and their id spaces overlap, so sending one without a provider can fail with `409` (see that response). Pass `?provider=` — every source market in `GET /v1/matching-markets/sports` carries the `provider` that goes with its `event_id`.
     *
     * **Sports identifiers expire.** Game tickers and slugs are delisted once an event settles, and a Hyperliquid id lives as long as its question: its daily-recurring price outcomes roll over every day, while a season-long question stays listed until it resolves. Take current ones from `GET /v1/matching-markets/sports` (every source market carries its provider's `event_id`) rather than copying one out of this reference.
     */
    eventId: string;
    /** Optional provider override, spelled like the `provider` field of this response and every other one (it was `platform` until 2026-10-09; `?platform=` now answers `400` naming this parameter). When omitted, inferred from the `event_id` format: `KX…` → Kalshi, `L\d+` → SX Bet. Numeric IDs and kebab-case slugs are shared shape between Polymarket and Predict; in that case the service probes both and returns `409` rather than guessing if the identifier resolves on both. Hyperliquid question/outcome integer ids collide with these numerics and are not inferred — pass `?provider=hyperliquid` (alias `hl`). Pred parent ids share the `0x…64hex` shape with SX Bet market hashes and are not inferred either — pass `?provider=pred`. Passing `provider` explicitly skips the probe entirely and is the recommended call whenever you know it. Supplying a value that contradicts a composite `{provider}:` prefix is a `400`. */
    provider?: PredictorSDK.GetEventRequestProvider;
}
