// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../index.js";

/**
 * @example
 *     {
 *         marketId: "kalshi:KXMLBGAME-26MAY262005HOUTEX-TEX"
 *     }
 */
export interface GetMarketRequest {
    /** Composite (`{provider}:{native_id}`) or platform-native market identifier. Examples per platform: Kalshi market ticker (`KXMLBGAME-26MAY262005HOUTEX-TEX`), Polymarket numeric id or slug (`540817` or `new-rhianna-album-before-gta-vi-926`), Predict market id (`356635`), SX Bet `marketHash` (`0x…64hex`). */
    marketId: string;
    /** Optional platform override. When omitted, inferred from the composite prefix or from the native ID format (`KX…` → Kalshi, `0x…64hex` → SX Bet). Numeric IDs and kebab-case slugs are shared shape between Polymarket and Predict; in that case the service probes Polymarket first and falls back to Predict on 404. Pass `platform` explicitly to skip the probe. When the override contradicts a composite prefix (e.g. `kalshi:X` with `?platform=polymarket`), the request returns 400. */
    platform?: PredictorSDK.GetMarketRequestPlatform;
}
