// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         address: "0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b"
 *     }
 */
export interface GetPolymarketWalletRequest {
    /** Wallet address to look up. May be a Polymarket proxy address or the underlying signer EOA — the endpoint resolves either form. Must match `^0x[a-fA-F0-9]{40}$`. Mixed-case input is accepted and lowercased in the response. Mutually exclusive with `username`; exactly one of the two is required. */
    address?: string;
    /** Polymarket display name to look up. Match is case-insensitive and exact against the user's stored `name` (so `Car`, `car`, and `CAR` all resolve, but `Theo` does not match `Theo47`). A leading `@` is accepted and stripped before the lookup. Mutually exclusive with `address`; exactly one of the two is required. Example: `Car`. */
    username?: string;
}
