// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../index.js";

/**
 * @example
 *     {}
 */
export interface GetSportsMatchingMarketsRequest {
    /** Maximum number of matched events to return per page. Range 1–100, default 25. Ignored in lookup mode, when `event_id` or `source_id` is supplied. */
    limit?: number;
    /** Opaque cursor from a previous response's `pagination.nextCursor` in the SDKs (raw JSON: `pagination.next_cursor`). Must be used with the same filter set — a cursor from `include_settled=true` cannot be replayed against `include_settled=false` and will return `400`. */
    cursor?: string;
    /**
     * Selects which events this request draws from, in list mode and in lookup mode alike. Defaults to `false`: only events whose scheduled start has not certainly passed — today's games, plus a one-day grace so a late start that runs past midnight Eastern is never dropped mid-play. Set it to `true` to also get events whose game date is further in the past, including ones a venue still lists as open.
     *
     * A venue can keep quoting a market for months after the game (a 94-day-old row was still `status: open` with a live two-sided book when this was written), so the endpoint filters on the game date it already holds — the trailing date of the canonical `event_id` — rather than on an upstream status it cannot verify. Nothing is reported as settled that the venue has not settled; these events are simply not *current*, which is what the default page is for.
     *
     * Because it selects the population, a lookup (`?event_id=` or `?source_id=`) for a past-dated event answers `200` with an empty `canonical_events` object unless this is `true`.
     */
    includeSettled?: boolean;
    /** Player-prop admission policy. Explicit use requires `include_submarkets=true`; otherwise returns 400. `strict` (the default) includes only groups of at least two distinct providers with verified player/game/stat/threshold/side identity and a completely reviewed equivalent settlement profile. `same_prop` retains exact prop identity but also admits different or unverified settlement rules, identified by `settlement_equivalence` and `rule_comparisons`. Unknown rules never prove equivalence. Applies in list and lookup mode, including `include_settled`; cursors cannot be reused between policies. Does not change game-line matching or the default moneyline projection. Historical snapshots without verified player identity do not expose props. */
    playerPropMatch?: PredictorSDK.GetSportsMatchingMarketsRequestPlayerPropMatch;
    /** When `true`, each event lists every matched submarket (spreads, totals, period lines and player props) instead of only its full-game moneyline. Every submarket has the same shape, so code written against the default reads the rest unchanged. This is an identity mapping only; fetch current status, quotes, and liquidity from the referenced market resources. Explicit `player_prop_match` requires this to be `true`. */
    includeSubmarkets?: boolean;
    /** Canonical event key(s) to look up directly (for example, `nba-okc-sas-2026-10-20`). Repeat the parameter for several events, and combine it freely with `source_id`, up to 100 unique identifiers in all. Lookup mode — pagination parameters are ignored. A provider identifier here is a `400`; send it as `source_id`. */
    eventId?: string | string[];
    /** Venue identifier(s) to look up, as `{provider}:{id}`: any `market_id`, `market_slug` or `event_id` that a `canonical_events[].submarkets[].source_markets[]` entry publishes, prefixed with that entry's `provider`. For example `kalshi:KXNBAGAME-26OCT20OKCSAS` (an event ticker), `kalshi:KXNBAGAME-26OCT20OKCSAS-OKC` (a market ticker), `sxbet:L19766755` (a fixture), or Pred's `pred:<parent_market_id>:<child_market_id>` pair. Only the text before the first colon is the provider, and it must be one of `kalshi`, `polymarket`, `predict`, `sxbet`, `alpha-arcade`, `prophetx` or `pred`; anything else is a `400`. Each matched event is keyed by the identifier exactly as sent (surrounding whitespace trimmed), so the keys of the response are the identifiers that matched. Repeat the parameter for several identifiers, across providers; combined with `event_id`, up to 100 unique identifiers in all. Lookup mode — pagination parameters are ignored. A lookup finds the event an identifier belongs to; set `include_submarkets=true` to see the submarket it names when that is not the moneyline. */
    sourceId?: string | string[];
}
