// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         address: "0x7c3db723f1d4d8cb9c550095203b686cb11e5c6b"
 *     }
 */
export interface ListPolymarketWalletPositionsRequest {
    /** Polymarket proxy wallet address. Must match `^0x[a-fA-F0-9]{40}$`. Mixed-case input is accepted and lowercased in the response. Mutually exclusive with `username`; exactly one of the two is required. */
    address?: string;
    /** Polymarket display name to resolve to a proxy wallet. Match is case-insensitive and exact against the user's stored `name`. A leading `@` is accepted and stripped. Mutually exclusive with `address`. */
    username?: string;
    /** Number of items requested for the first page. Defaults to 50. Once a cursor is supplied, the cursor's page size is used. */
    limit?: number;
    /** Opaque cursor from a previous response's `pagination.next_cursor`. Bound to the resolved wallet address — replaying a cursor against a different wallet returns `400`. Cursors issued by the previous offset-based implementation are rejected; restart from the first page. A cursor cannot carry a page size above 100. */
    cursor?: string;
}
