// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AmbiguousIdentifierError: core.serialization.ObjectSchema<
    serializers.AmbiguousIdentifierError.Raw,
    PredictorSDK.AmbiguousIdentifierError
> = core.serialization.object({
    error: core.serialization.string(),
    message: core.serialization.string().optional(),
    candidates: core.serialization.list(core.serialization.string()),
    statusCode: core.serialization.property("status_code", core.serialization.number()),
});

export declare namespace AmbiguousIdentifierError {
    export interface Raw {
        error: string;
        message?: string | null;
        candidates: string[];
        status_code: number;
    }
}
