// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CanonicalSportsSubmarketSettlementEquivalence: core.serialization.Schema<
    serializers.CanonicalSportsSubmarketSettlementEquivalence.Raw,
    PredictorSDK.CanonicalSportsSubmarketSettlementEquivalence
> = core.serialization.enum_(["equivalent", "different", "unverified"]);

export declare namespace CanonicalSportsSubmarketSettlementEquivalence {
    export type Raw = "equivalent" | "different" | "unverified";
}
