// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CanonicalSportsOutcome } from "./CanonicalSportsOutcome.js";
import { CanonicalSportsRules } from "./CanonicalSportsRules.js";
import { CanonicalSportsSourceMarket } from "./CanonicalSportsSourceMarket.js";
import { CanonicalSportsSubject } from "./CanonicalSportsSubject.js";

export const CanonicalSportsSubmarket: core.serialization.ObjectSchema<
    serializers.CanonicalSportsSubmarket.Raw,
    PredictorSDK.CanonicalSportsSubmarket
> = core.serialization.object({
    key: core.serialization.string(),
    marketType: core.serialization.property("market_type", core.serialization.string()),
    segment: core.serialization.string(),
    displayName: core.serialization.property("display_name", core.serialization.string().optional()),
    metric: core.serialization.string().optional(),
    line: core.serialization.number().optional(),
    subject: CanonicalSportsSubject.optional(),
    rules: CanonicalSportsRules.optional(),
    outcomes: core.serialization.list(CanonicalSportsOutcome),
    sourceMarkets: core.serialization.property("source_markets", core.serialization.list(CanonicalSportsSourceMarket)),
});

export declare namespace CanonicalSportsSubmarket {
    export interface Raw {
        key: string;
        market_type: string;
        segment: string;
        display_name?: string | null;
        metric?: string | null;
        line?: number | null;
        subject?: CanonicalSportsSubject.Raw | null;
        rules?: CanonicalSportsRules.Raw | null;
        outcomes: CanonicalSportsOutcome.Raw[];
        source_markets: CanonicalSportsSourceMarket.Raw[];
    }
}
