// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CanonicalSportsSourceMarketProvider } from "./CanonicalSportsSourceMarketProvider.js";
import { CanonicalSportsSourceOutcome } from "./CanonicalSportsSourceOutcome.js";

export const CanonicalSportsSourceMarket: core.serialization.ObjectSchema<
    serializers.CanonicalSportsSourceMarket.Raw,
    PredictorSDK.CanonicalSportsSourceMarket
> = core.serialization.object({
    provider: CanonicalSportsSourceMarketProvider,
    marketId: core.serialization.property("market_id", core.serialization.string()),
    marketName: core.serialization.property("market_name", core.serialization.string().optional()),
    marketSlug: core.serialization.property("market_slug", core.serialization.string().optional()),
    outcomes: core.serialization.list(CanonicalSportsSourceOutcome),
});

export declare namespace CanonicalSportsSourceMarket {
    export interface Raw {
        provider: CanonicalSportsSourceMarketProvider.Raw;
        market_id: string;
        market_name?: string | null;
        market_slug?: string | null;
        outcomes: CanonicalSportsSourceOutcome.Raw[];
    }
}
