// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CanonicalSportsSourceOutcome: core.serialization.ObjectSchema<
    serializers.CanonicalSportsSourceOutcome.Raw,
    PredictorSDK.CanonicalSportsSourceOutcome
> = core.serialization.object({
    canonicalOutcomeKey: core.serialization.property("canonical_outcome_key", core.serialization.string()),
    label: core.serialization.string(),
    outcomeId: core.serialization.property("outcome_id", core.serialization.string()),
    side: core.serialization.string().optional(),
});

export declare namespace CanonicalSportsSourceOutcome {
    export interface Raw {
        canonical_outcome_key: string;
        label: string;
        outcome_id: string;
        side?: string | null;
    }
}
