// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CanonicalSportsRules: core.serialization.ObjectSchema<
    serializers.CanonicalSportsRules.Raw,
    PredictorSDK.CanonicalSportsRules
> = core.serialization.object({
    settlement: core.serialization.string().optional(),
});

export declare namespace CanonicalSportsRules {
    export interface Raw {
        settlement?: string | null;
    }
}
