// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CanonicalSportsSubject: core.serialization.ObjectSchema<
    serializers.CanonicalSportsSubject.Raw,
    PredictorSDK.CanonicalSportsSubject
> = core.serialization.object({
    type: core.serialization.string(),
    key: core.serialization.string(),
    name: core.serialization.string().optional(),
    team: core.serialization.string().optional(),
});

export declare namespace CanonicalSportsSubject {
    export interface Raw {
        type: string;
        key: string;
        name?: string | null;
        team?: string | null;
    }
}
