// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CanonicalSportsOutcome: core.serialization.ObjectSchema<
    serializers.CanonicalSportsOutcome.Raw,
    PredictorSDK.CanonicalSportsOutcome
> = core.serialization.object({
    key: core.serialization.string(),
    label: core.serialization.string(),
    type: core.serialization.string().optional(),
    side: core.serialization.string().optional(),
});

export declare namespace CanonicalSportsOutcome {
    export interface Raw {
        key: string;
        label: string;
        type?: string | null;
        side?: string | null;
    }
}
