// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CanonicalSportsParticipant } from "./CanonicalSportsParticipant.js";
import { CanonicalSportsSubmarket } from "./CanonicalSportsSubmarket.js";

export const CanonicalSportsEvent: core.serialization.ObjectSchema<
    serializers.CanonicalSportsEvent.Raw,
    PredictorSDK.CanonicalSportsEvent
> = core.serialization.object({
    eventId: core.serialization.property("event_id", core.serialization.string()),
    sport: core.serialization.string().optional(),
    league: core.serialization.string().optional(),
    title: core.serialization.string(),
    participants: core.serialization.list(CanonicalSportsParticipant).optional(),
    submarkets: core.serialization.list(CanonicalSportsSubmarket),
});

export declare namespace CanonicalSportsEvent {
    export interface Raw {
        event_id: string;
        sport?: string | null;
        league?: string | null;
        title: string;
        participants?: CanonicalSportsParticipant.Raw[] | null;
        submarkets: CanonicalSportsSubmarket.Raw[];
    }
}
