// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CanonicalSportsParticipant: core.serialization.ObjectSchema<
    serializers.CanonicalSportsParticipant.Raw,
    PredictorSDK.CanonicalSportsParticipant
> = core.serialization.object({
    key: core.serialization.string(),
    name: core.serialization.string().optional(),
    role: core.serialization.string().optional(),
});

export declare namespace CanonicalSportsParticipant {
    export interface Raw {
        key: string;
        name?: string | null;
        role?: string | null;
    }
}
