// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { MarketCategory } from "./MarketCategory.js";

export const CategoryInfo: core.serialization.ObjectSchema<serializers.CategoryInfo.Raw, PredictorSDK.CategoryInfo> =
    core.serialization.object({
        id: MarketCategory,
        name: core.serialization.string(),
        description: core.serialization.string(),
    });

export declare namespace CategoryInfo {
    export interface Raw {
        id: MarketCategory.Raw;
        name: string;
        description: string;
    }
}
