// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CategoryInfo } from "./CategoryInfo.js";

export const CategoriesResponse: core.serialization.ObjectSchema<
    serializers.CategoriesResponse.Raw,
    PredictorSDK.CategoriesResponse
> = core.serialization.object({
    data: core.serialization.list(CategoryInfo),
});

export declare namespace CategoriesResponse {
    export interface Raw {
        data: CategoryInfo.Raw[];
    }
}
