// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CryptoPriceItem } from "./CryptoPriceItem.js";
import { PaginationBlock } from "./PaginationBlock.js";

export const CryptoPricesResponse: core.serialization.ObjectSchema<
    serializers.CryptoPricesResponse.Raw,
    PredictorSDK.CryptoPricesResponse
> = core.serialization.object({
    data: core.serialization.list(CryptoPriceItem),
    pagination: PaginationBlock,
});

export declare namespace CryptoPricesResponse {
    export interface Raw {
        data: CryptoPriceItem.Raw[];
        pagination: PaginationBlock.Raw;
    }
}
