// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const CryptoPriceItem: core.serialization.ObjectSchema<
    serializers.CryptoPriceItem.Raw,
    PredictorSDK.CryptoPriceItem
> = core.serialization.object({
    symbol: core.serialization.string(),
    value: core.serialization.number(),
    timestamp: core.serialization.number(),
});

export declare namespace CryptoPriceItem {
    export interface Raw {
        symbol: string;
        value: number;
        timestamp: number;
    }
}
