// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ErrorParamProblem: core.serialization.ObjectSchema<
    serializers.ErrorParamProblem.Raw,
    PredictorSDK.ErrorParamProblem
> = core.serialization.object({
    param: core.serialization.string(),
    value: core.serialization.string(),
    message: core.serialization.string(),
});

export declare namespace ErrorParamProblem {
    export interface Raw {
        param: string;
        value: string;
        message: string;
    }
}
