// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ErrorResponse: core.serialization.ObjectSchema<serializers.ErrorResponse.Raw, PredictorSDK.ErrorResponse> =
    core.serialization.object({
        error: core.serialization.string(),
        statusCode: core.serialization.property("status_code", core.serialization.number()),
    });

export declare namespace ErrorResponse {
    export interface Raw {
        error: string;
        status_code: number;
    }
}
