// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const EventMarket: core.serialization.ObjectSchema<serializers.EventMarket.Raw, PredictorSDK.EventMarket> =
    core.serialization.object({
        marketId: core.serialization.property("market_id", core.serialization.string()),
        title: core.serialization.string(),
    });

export declare namespace EventMarket {
    export interface Raw {
        market_id: string;
        title: string;
    }
}
