// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const EventFanout: core.serialization.ObjectSchema<serializers.EventFanout.Raw, PredictorSDK.EventFanout> =
    core.serialization.object({
        siblingsAttempted: core.serialization.property(
            "siblings_attempted",
            core.serialization.list(core.serialization.string()),
        ),
        siblingsReturned: core.serialization.property(
            "siblings_returned",
            core.serialization.list(core.serialization.string()),
        ),
        siblingsMissing: core.serialization.property(
            "siblings_missing",
            core.serialization.list(core.serialization.string()),
        ),
    });

export declare namespace EventFanout {
    export interface Raw {
        siblings_attempted: string[];
        siblings_returned: string[];
        siblings_missing: string[];
    }
}
