// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { EventFanout } from "./EventFanout.js";
import { EventMarket } from "./EventMarket.js";
import { EventResponsePlatform } from "./EventResponsePlatform.js";

export const EventResponse: core.serialization.ObjectSchema<serializers.EventResponse.Raw, PredictorSDK.EventResponse> =
    core.serialization.object({
        eventId: core.serialization.property("event_id", core.serialization.string()),
        platform: EventResponsePlatform,
        title: core.serialization.string(),
        markets: core.serialization.list(EventMarket),
        fanout: EventFanout.optional(),
    });

export declare namespace EventResponse {
    export interface Raw {
        event_id: string;
        platform: EventResponsePlatform.Raw;
        title: string;
        markets: EventMarket.Raw[];
        fanout?: EventFanout.Raw | null;
    }
}
