// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const GetEventRequestProvider: core.serialization.Schema<
    serializers.GetEventRequestProvider.Raw,
    PredictorSDK.GetEventRequestProvider
> = core.serialization.enum_([
    "kalshi",
    "polymarket",
    "predict",
    "sxbet",
    "hyperliquid",
    "alpha-arcade",
    "prophetx",
    "limitless",
    "pred",
]);

export declare namespace GetEventRequestProvider {
    export type Raw =
        | "kalshi"
        | "polymarket"
        | "predict"
        | "sxbet"
        | "hyperliquid"
        | "alpha-arcade"
        | "prophetx"
        | "limitless"
        | "pred";
}
