// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const GetSportsMatchingMarketsRequestLeague: core.serialization.Schema<
    serializers.GetSportsMatchingMarketsRequestLeague.Raw,
    PredictorSDK.GetSportsMatchingMarketsRequestLeague
> = core.serialization.enum_(["nba", "wnba", "nfl", "mlb", "nhl"]);

export declare namespace GetSportsMatchingMarketsRequestLeague {
    export type Raw = "nba" | "wnba" | "nfl" | "mlb" | "nhl";
}
