// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const GetSportsMatchingMarketsRequestPlayerPropMatch: core.serialization.Schema<
    serializers.GetSportsMatchingMarketsRequestPlayerPropMatch.Raw,
    PredictorSDK.GetSportsMatchingMarketsRequestPlayerPropMatch
> = core.serialization.enum_(["strict", "same_prop"]);

export declare namespace GetSportsMatchingMarketsRequestPlayerPropMatch {
    export type Raw = "strict" | "same_prop";
}
