// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { MarketDetailOutcome } from "./MarketDetailOutcome.js";
import { MarketDetailResponseProvider } from "./MarketDetailResponseProvider.js";
import { MarketDetailResponseStatus } from "./MarketDetailResponseStatus.js";

export const MarketDetailResponse: core.serialization.ObjectSchema<
    serializers.MarketDetailResponse.Raw,
    PredictorSDK.MarketDetailResponse
> = core.serialization.object({
    id: core.serialization.string(),
    provider: MarketDetailResponseProvider,
    providerId: core.serialization.property("provider_id", core.serialization.string()),
    title: core.serialization.string(),
    status: MarketDetailResponseStatus,
    outcomes: core.serialization.list(MarketDetailOutcome),
});

export declare namespace MarketDetailResponse {
    export interface Raw {
        id: string;
        provider: MarketDetailResponseProvider.Raw;
        provider_id: string;
        title: string;
        status: MarketDetailResponseStatus.Raw;
        outcomes: MarketDetailOutcome.Raw[];
    }
}
