// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { MarketDetailOutcome } from "./MarketDetailOutcome.js";
import { MarketDetailPricing } from "./MarketDetailPricing.js";
import { MarketDetailResponseProvider } from "./MarketDetailResponseProvider.js";
import { MarketDetailResponseStatus } from "./MarketDetailResponseStatus.js";

export const MarketDetailResponse: core.serialization.ObjectSchema<
    serializers.MarketDetailResponse.Raw,
    PredictorSDK.MarketDetailResponse
> = core.serialization.object({
    id: core.serialization.string(),
    provider: MarketDetailResponseProvider,
    providerId: core.serialization.property("provider_id", core.serialization.string()),
    title: core.serialization.string(),
    status: MarketDetailResponseStatus,
    outcomes: core.serialization.list(MarketDetailOutcome),
    pricing: MarketDetailPricing,
    liquidityUsd: core.serialization.property("liquidity_usd", core.serialization.number().nullable()),
    volume24HUsd: core.serialization.property("volume_24h_usd", core.serialization.number().nullable()),
    volumeTotalUsd: core.serialization.property("volume_total_usd", core.serialization.number().nullable()),
    volume24HContracts: core.serialization.property("volume_24h_contracts", core.serialization.number().optional()),
    volumeTotalContracts: core.serialization.property("volume_total_contracts", core.serialization.number().optional()),
    openInterest: core.serialization.property("open_interest", core.serialization.number().optional()),
});

export declare namespace MarketDetailResponse {
    export interface Raw {
        id: string;
        provider: MarketDetailResponseProvider.Raw;
        provider_id: string;
        title: string;
        status: MarketDetailResponseStatus.Raw;
        outcomes: MarketDetailOutcome.Raw[];
        pricing: MarketDetailPricing.Raw;
        liquidity_usd?: number | null;
        volume_24h_usd?: number | null;
        volume_total_usd?: number | null;
        volume_24h_contracts?: number | null;
        volume_total_contracts?: number | null;
        open_interest?: number | null;
    }
}
