// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { MarketDetailFeeLeg } from "./MarketDetailFeeLeg.js";
import { MarketDetailScheduledFeeChange } from "./MarketDetailScheduledFeeChange.js";
import { MarketDetailTradingFeesAvailability } from "./MarketDetailTradingFeesAvailability.js";
import { MarketDetailTradingFeesChargeBasis } from "./MarketDetailTradingFeesChargeBasis.js";
import { MarketDetailTradingFeesSource } from "./MarketDetailTradingFeesSource.js";

export const MarketDetailTradingFees: core.serialization.ObjectSchema<
    serializers.MarketDetailTradingFees.Raw,
    PredictorSDK.MarketDetailTradingFees
> = core.serialization.object({
    availability: MarketDetailTradingFeesAvailability,
    observedAt: core.serialization.property("observed_at", core.serialization.date().nullable()),
    source: MarketDetailTradingFeesSource,
    chargeBasis: core.serialization.property("charge_basis", MarketDetailTradingFeesChargeBasis.nullable()),
    taker: MarketDetailFeeLeg.nullable(),
    maker: MarketDetailFeeLeg.nullable(),
    scheduledChange: core.serialization.property("scheduled_change", MarketDetailScheduledFeeChange.optionalNullable()),
});

export declare namespace MarketDetailTradingFees {
    export interface Raw {
        availability: MarketDetailTradingFeesAvailability.Raw;
        observed_at?: string | null;
        source: MarketDetailTradingFeesSource.Raw;
        charge_basis?: MarketDetailTradingFeesChargeBasis.Raw | null;
        taker?: MarketDetailFeeLeg.Raw | null;
        maker?: MarketDetailFeeLeg.Raw | null;
        scheduled_change?: (MarketDetailScheduledFeeChange.Raw | null | undefined) | null;
    }
}
