// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const MarketDetailTradingFeesChargeBasis: core.serialization.Schema<
    serializers.MarketDetailTradingFeesChargeBasis.Raw,
    PredictorSDK.MarketDetailTradingFeesChargeBasis
> = core.serialization.enum_(["fill", "settlement_profit"]);

export declare namespace MarketDetailTradingFeesChargeBasis {
    export type Raw = "fill" | "settlement_profit";
}
