// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const MarketDetailResponseProvider: core.serialization.Schema<
    serializers.MarketDetailResponseProvider.Raw,
    PredictorSDK.MarketDetailResponseProvider
> = core.serialization.enum_(["kalshi", "polymarket", "predict", "sxbet"]);

export declare namespace MarketDetailResponseProvider {
    export type Raw = "kalshi" | "polymarket" | "predict" | "sxbet";
}
