// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const MarketDetailPricingSource: core.serialization.Schema<
    serializers.MarketDetailPricingSource.Raw,
    PredictorSDK.MarketDetailPricingSource
> = core.serialization.enum_(["market_record", "orderbook"]);

export declare namespace MarketDetailPricingSource {
    export type Raw = "market_record" | "orderbook";
}
