// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const MarketsSnapshot: core.serialization.ObjectSchema<
    serializers.MarketsSnapshot.Raw,
    PredictorSDK.MarketsSnapshot
> = core.serialization.object({
    observedAt: core.serialization.property("observed_at", core.serialization.date().nullable()),
});

export declare namespace MarketsSnapshot {
    export interface Raw {
        observed_at?: string | null;
    }
}
