// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const MarketDetailPricingAvailability: core.serialization.Schema<
    serializers.MarketDetailPricingAvailability.Raw,
    PredictorSDK.MarketDetailPricingAvailability
> = core.serialization.enum_(["live", "partial", "no_quotes", "unavailable"]);

export declare namespace MarketDetailPricingAvailability {
    export type Raw = "live" | "partial" | "no_quotes" | "unavailable";
}
