// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const MarketDetailPricingScale: core.serialization.Schema<
    serializers.MarketDetailPricingScale.Raw,
    PredictorSDK.MarketDetailPricingScale
> = core.serialization.enum_(["probability_0_1"]);

export declare namespace MarketDetailPricingScale {
    export type Raw = "probability_0_1";
}
