// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const MarketDetailPricingAsOfKind: core.serialization.Schema<
    serializers.MarketDetailPricingAsOfKind.Raw,
    PredictorSDK.MarketDetailPricingAsOfKind
> = core.serialization.enum_(["quote", "record_refresh", "record_static", "unknown"]);

export declare namespace MarketDetailPricingAsOfKind {
    export type Raw = "quote" | "record_refresh" | "record_static" | "unknown";
}
