// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const MarketCategory: core.serialization.Schema<serializers.MarketCategory.Raw, PredictorSDK.MarketCategory> =
    core.serialization.enum_([
        "sports",
        "politics",
        "crypto",
        "finance",
        "economics",
        "weather",
        "culture",
        "technology",
        "entertainment",
        "other",
        "unknown",
    ]);

export declare namespace MarketCategory {
    export type Raw =
        | "sports"
        | "politics"
        | "crypto"
        | "finance"
        | "economics"
        | "weather"
        | "culture"
        | "technology"
        | "entertainment"
        | "other"
        | "unknown";
}
