// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const MarketDetailFeeRoundingDirection: core.serialization.Schema<
    serializers.MarketDetailFeeRoundingDirection.Raw,
    PredictorSDK.MarketDetailFeeRoundingDirection
> = core.serialization.enum_(["up", "nearest"]);

export declare namespace MarketDetailFeeRoundingDirection {
    export type Raw = "up" | "nearest";
}
