// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { MarketDetailFeeLegModel } from "./MarketDetailFeeLegModel.js";
import { MarketDetailFeeRounding } from "./MarketDetailFeeRounding.js";

export const MarketDetailFeeLeg: core.serialization.ObjectSchema<
    serializers.MarketDetailFeeLeg.Raw,
    PredictorSDK.MarketDetailFeeLeg
> = core.serialization.object({
    model: MarketDetailFeeLegModel,
    rate: core.serialization.number().nullable(),
    exponent: core.serialization.number().nullable(),
    rounding: MarketDetailFeeRounding.nullable(),
});

export declare namespace MarketDetailFeeLeg {
    export interface Raw {
        model: MarketDetailFeeLegModel.Raw;
        rate?: number | null;
        exponent?: number | null;
        rounding?: MarketDetailFeeRounding.Raw | null;
    }
}
