// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { MarketDetailFeeLeg } from "./MarketDetailFeeLeg.js";

export const MarketDetailScheduledFeeChange: core.serialization.ObjectSchema<
    serializers.MarketDetailScheduledFeeChange.Raw,
    PredictorSDK.MarketDetailScheduledFeeChange
> = core.serialization.object({
    effectiveAt: core.serialization.property("effective_at", core.serialization.date()),
    taker: MarketDetailFeeLeg.nullable(),
    maker: MarketDetailFeeLeg.nullable(),
});

export declare namespace MarketDetailScheduledFeeChange {
    export interface Raw {
        effective_at: string;
        taker?: MarketDetailFeeLeg.Raw | null;
        maker?: MarketDetailFeeLeg.Raw | null;
    }
}
