// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { MarketDetailFeeRoundingDirection } from "./MarketDetailFeeRoundingDirection.js";

export const MarketDetailFeeRounding: core.serialization.ObjectSchema<
    serializers.MarketDetailFeeRounding.Raw,
    PredictorSDK.MarketDetailFeeRounding
> = core.serialization.object({
    direction: MarketDetailFeeRoundingDirection,
    increment: core.serialization.number(),
});

export declare namespace MarketDetailFeeRounding {
    export interface Raw {
        direction: MarketDetailFeeRoundingDirection.Raw;
        increment: number;
    }
}
