// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { MarketsSnapshot } from "./MarketsSnapshot.js";
import { PaginationBlock } from "./PaginationBlock.js";
import { UnifiedMarket } from "./UnifiedMarket.js";

export const MarketsListResponse: core.serialization.ObjectSchema<
    serializers.MarketsListResponse.Raw,
    PredictorSDK.MarketsListResponse
> = core.serialization.object({
    data: core.serialization.list(UnifiedMarket),
    snapshot: MarketsSnapshot,
    pagination: PaginationBlock,
});

export declare namespace MarketsListResponse {
    export interface Raw {
        data: UnifiedMarket.Raw[];
        snapshot: MarketsSnapshot.Raw;
        pagination: PaginationBlock.Raw;
    }
}
