// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const MarketDetailTradingFeesSource: core.serialization.Schema<
    serializers.MarketDetailTradingFeesSource.Raw,
    PredictorSDK.MarketDetailTradingFeesSource
> = core.serialization.enum_(["market_record", "series_record", "venue_schedule"]);

export declare namespace MarketDetailTradingFeesSource {
    export type Raw = "market_record" | "series_record" | "venue_schedule";
}
