// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const MarketDetailResponseStatus: core.serialization.Schema<
    serializers.MarketDetailResponseStatus.Raw,
    PredictorSDK.MarketDetailResponseStatus
> = core.serialization.enum_(["open", "closed", "settled"]);

export declare namespace MarketDetailResponseStatus {
    export type Raw = "open" | "closed" | "settled";
}
