// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const MarketDetailFeeLegModel: core.serialization.Schema<
    serializers.MarketDetailFeeLegModel.Raw,
    PredictorSDK.MarketDetailFeeLegModel
> = core.serialization.enum_(["quadratic", "min_price", "notional", "none"]);

export declare namespace MarketDetailFeeLegModel {
    export type Raw = "quadratic" | "min_price" | "notional" | "none";
}
