// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PaginationBlock: core.serialization.ObjectSchema<
    serializers.PaginationBlock.Raw,
    PredictorSDK.PaginationBlock
> = core.serialization.object({
    limit: core.serialization.number(),
    total: core.serialization.number(),
    hasMore: core.serialization.property("has_more", core.serialization.boolean()),
    nextCursor: core.serialization.property("next_cursor", core.serialization.string().optional()),
});

export declare namespace PaginationBlock {
    export interface Raw {
        limit: number;
        total: number;
        has_more: boolean;
        next_cursor?: string | null;
    }
}
