// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PaymentRequiredErrorAction: core.serialization.Schema<
    serializers.PaymentRequiredErrorAction.Raw,
    PredictorSDK.PaymentRequiredErrorAction
> = core.serialization.enum_(["upgrade_plan", "resolve_payment"]);

export declare namespace PaymentRequiredErrorAction {
    export type Raw = "upgrade_plan" | "resolve_payment";
}
