// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { PaymentRequiredErrorAction } from "./PaymentRequiredErrorAction.js";

export const PaymentRequiredErrorBody: core.serialization.ObjectSchema<
    serializers.PaymentRequiredErrorBody.Raw,
    PredictorSDK.PaymentRequiredErrorBody
> = core.serialization.object({
    error: core.serialization.string(),
    message: core.serialization.string().optional(),
    statusCode: core.serialization.property("status_code", core.serialization.number()),
    action: PaymentRequiredErrorAction,
    requiredTier: core.serialization.property("required_tier", core.serialization.string()),
    currentTier: core.serialization.property("current_tier", core.serialization.string()),
    includedRequestsPerMonth: core.serialization.property(
        "included_requests_per_month",
        core.serialization.number().optional(),
    ),
    currentPeriodRequests: core.serialization.property(
        "current_period_requests",
        core.serialization.number().optional(),
    ),
});

export declare namespace PaymentRequiredErrorBody {
    export interface Raw {
        error: string;
        message?: string | null;
        status_code: number;
        action: PaymentRequiredErrorAction.Raw;
        required_tier: string;
        current_tier: string;
        included_requests_per_month?: number | null;
        current_period_requests?: number | null;
    }
}
