// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const Plan: core.serialization.ObjectSchema<serializers.Plan.Raw, PredictorSDK.Plan> = core.serialization.object(
    {
        key: core.serialization.string(),
        name: core.serialization.string(),
        billingTier: core.serialization.property("billing_tier", core.serialization.string()),
        trialDays: core.serialization.property("trial_days", core.serialization.number()),
        tagline: core.serialization.string(),
        monthlyPriceCents: core.serialization.property("monthly_price_cents", core.serialization.number()),
        includedRequestsPerMonth: core.serialization.property(
            "included_requests_per_month",
            core.serialization.number(),
        ),
        overageCentsPer1K: core.serialization.property("overage_cents_per_1k", core.serialization.number()),
        rateLimitPerMin: core.serialization.property("rate_limit_per_min", core.serialization.number()),
        maxKeys: core.serialization.property("max_keys", core.serialization.number()),
        features: core.serialization.list(core.serialization.string()),
        ctaLabel: core.serialization.property("cta_label", core.serialization.string()),
        highlighted: core.serialization.boolean(),
        contactSales: core.serialization.property("contact_sales", core.serialization.boolean()),
    },
);

export declare namespace Plan {
    export interface Raw {
        key: string;
        name: string;
        billing_tier: string;
        trial_days: number;
        tagline: string;
        monthly_price_cents: number;
        included_requests_per_month: number;
        overage_cents_per_1k: number;
        rate_limit_per_min: number;
        max_keys: number;
        features: string[];
        cta_label: string;
        highlighted: boolean;
        contact_sales: boolean;
    }
}
