// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Plan } from "./Plan.js";

export const PlansResponse: core.serialization.ObjectSchema<serializers.PlansResponse.Raw, PredictorSDK.PlansResponse> =
    core.serialization.object({
        data: core.serialization.list(Plan),
    });

export declare namespace PlansResponse {
    export interface Raw {
        data: Plan.Raw[];
    }
}
