// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PlatformMarketPlatform: core.serialization.Schema<
    serializers.PlatformMarketPlatform.Raw,
    PredictorSDK.PlatformMarketPlatform
> = core.serialization.enum_(["KALSHI", "POLYMARKET", "PREDICT", "SXBET"]);

export declare namespace PlatformMarketPlatform {
    export type Raw = "KALSHI" | "POLYMARKET" | "PREDICT" | "SXBET";
}
