// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { PlatformMarketPlatform } from "./PlatformMarketPlatform.js";

export const PlatformMarket: core.serialization.ObjectSchema<
    serializers.PlatformMarket.Raw,
    PredictorSDK.PlatformMarket
> = core.serialization.object({
    platform: PlatformMarketPlatform,
    eventTicker: core.serialization.property("event_ticker", core.serialization.string().optional()),
    marketTickers: core.serialization.property(
        "market_tickers",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    marketSlug: core.serialization.property("market_slug", core.serialization.string().optional()),
    tokenIds: core.serialization.property("token_ids", core.serialization.list(core.serialization.string()).optional()),
    marketId: core.serialization.property("market_id", core.serialization.string().optional()),
    outcomeIds: core.serialization.property(
        "outcome_ids",
        core.serialization.list(core.serialization.string()).optional(),
    ),
});

export declare namespace PlatformMarket {
    export interface Raw {
        platform: PlatformMarketPlatform.Raw;
        event_ticker?: string | null;
        market_tickers?: string[] | null;
        market_slug?: string | null;
        token_ids?: string[] | null;
        market_id?: string | null;
        outcome_ids?: string[] | null;
    }
}
