// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PlayerPropRuleSourceValue: core.serialization.ObjectSchema<
    serializers.PlayerPropRuleSourceValue.Raw,
    PredictorSDK.PlayerPropRuleSourceValue
> = core.serialization.object({
    provider: core.serialization.string(),
    marketId: core.serialization.property("market_id", core.serialization.string()),
    value: core.serialization.string(),
    description: core.serialization.string(),
    evidenceUrl: core.serialization.property("evidence_url", core.serialization.string().optional()),
});

export declare namespace PlayerPropRuleSourceValue {
    export interface Raw {
        provider: string;
        market_id: string;
        value: string;
        description: string;
        evidence_url?: string | null;
    }
}
