// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { PlayerPropRuleComparisonComparison } from "./PlayerPropRuleComparisonComparison.js";
import { PlayerPropRuleComparisonRule } from "./PlayerPropRuleComparisonRule.js";
import { PlayerPropRuleSourceValue } from "./PlayerPropRuleSourceValue.js";

export const PlayerPropRuleComparison: core.serialization.ObjectSchema<
    serializers.PlayerPropRuleComparison.Raw,
    PredictorSDK.PlayerPropRuleComparison
> = core.serialization.object({
    rule: PlayerPropRuleComparisonRule,
    label: core.serialization.string(),
    comparison: PlayerPropRuleComparisonComparison,
    sourceValues: core.serialization.property("source_values", core.serialization.list(PlayerPropRuleSourceValue)),
});

export declare namespace PlayerPropRuleComparison {
    export interface Raw {
        rule: PlayerPropRuleComparisonRule.Raw;
        label: string;
        comparison: PlayerPropRuleComparisonComparison.Raw;
        source_values: PlayerPropRuleSourceValue.Raw[];
    }
}
