// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PlayerPropRuleComparisonComparison: core.serialization.Schema<
    serializers.PlayerPropRuleComparisonComparison.Raw,
    PredictorSDK.PlayerPropRuleComparisonComparison
> = core.serialization.enum_(["equivalent", "different", "unverified"]);

export declare namespace PlayerPropRuleComparisonComparison {
    export type Raw = "equivalent" | "different" | "unverified";
}
