// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PlayerPropRuleComparisonRule: core.serialization.Schema<
    serializers.PlayerPropRuleComparisonRule.Raw,
    PredictorSDK.PlayerPropRuleComparisonRule
> = core.serialization.enum_([
    "non_participation",
    "overtime",
    "stat_definition",
    "threshold",
    "stat_corrections",
    "postponement",
    "cancellation",
    "interruption",
    "resolution_source",
]);

export declare namespace PlayerPropRuleComparisonRule {
    export type Raw =
        | "non_participation"
        | "overtime"
        | "stat_definition"
        | "threshold"
        | "stat_corrections"
        | "postponement"
        | "cancellation"
        | "interruption"
        | "resolution_source";
}
