// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PolymarketWalletResponse: core.serialization.ObjectSchema<
    serializers.PolymarketWalletResponse.Raw,
    PredictorSDK.PolymarketWalletResponse
> = core.serialization.object({
    address: core.serialization.string(),
    signer: core.serialization.string().nullable(),
    profileImage: core.serialization.property("profile_image", core.serialization.string().nullable()),
    displayName: core.serialization.property("display_name", core.serialization.string().nullable()),
});

export declare namespace PolymarketWalletResponse {
    export interface Raw {
        address: string;
        signer?: string | null;
        profile_image?: string | null;
        display_name?: string | null;
    }
}
