// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const PolymarketPosition: core.serialization.ObjectSchema<
    serializers.PolymarketPosition.Raw,
    PredictorSDK.PolymarketPosition
> = core.serialization.object({
    conditionId: core.serialization.property("condition_id", core.serialization.string()),
    outcome: core.serialization.string(),
    shares: core.serialization.number(),
});

export declare namespace PolymarketPosition {
    export interface Raw {
        condition_id: string;
        outcome: string;
        shares: number;
    }
}
