// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { PaginationBlock } from "./PaginationBlock.js";
import { PolymarketPosition } from "./PolymarketPosition.js";

export const PolymarketPositionsResponse: core.serialization.ObjectSchema<
    serializers.PolymarketPositionsResponse.Raw,
    PredictorSDK.PolymarketPositionsResponse
> = core.serialization.object({
    address: core.serialization.string(),
    data: core.serialization.list(PolymarketPosition),
    pagination: PaginationBlock,
});

export declare namespace PolymarketPositionsResponse {
    export interface Raw {
        address: string;
        data: PolymarketPosition.Raw[];
        pagination: PaginationBlock.Raw;
    }
}
