// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CanonicalSportsEvent } from "./CanonicalSportsEvent.js";
import { PaginationBlock } from "./PaginationBlock.js";
import { SportsMatchingSnapshot } from "./SportsMatchingSnapshot.js";

export const SportsMatchingListResponse: core.serialization.ObjectSchema<
    serializers.SportsMatchingListResponse.Raw,
    PredictorSDK.SportsMatchingListResponse
> = core.serialization.object({
    data: core.serialization.list(CanonicalSportsEvent),
    pagination: PaginationBlock,
    snapshot: SportsMatchingSnapshot,
});

export declare namespace SportsMatchingListResponse {
    export interface Raw {
        data: CanonicalSportsEvent.Raw[];
        pagination: PaginationBlock.Raw;
        snapshot: SportsMatchingSnapshot.Raw;
    }
}
