// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CanonicalSportsEvent } from "./CanonicalSportsEvent.js";
import { PaginationBlock } from "./PaginationBlock.js";
import { SportsMatchingLookup } from "./SportsMatchingLookup.js";
import { SportsMatchingSnapshot } from "./SportsMatchingSnapshot.js";

export const SportsMatchingResponse: core.serialization.ObjectSchema<
    serializers.SportsMatchingResponse.Raw,
    PredictorSDK.SportsMatchingResponse
> = core.serialization.object({
    data: core.serialization.list(CanonicalSportsEvent),
    lookups: core.serialization.record(core.serialization.string(), SportsMatchingLookup).optional(),
    pagination: PaginationBlock.optional(),
    snapshot: SportsMatchingSnapshot,
});

export declare namespace SportsMatchingResponse {
    export interface Raw {
        data: CanonicalSportsEvent.Raw[];
        lookups?: Record<string, SportsMatchingLookup.Raw> | null;
        pagination?: PaginationBlock.Raw | null;
        snapshot: SportsMatchingSnapshot.Raw;
    }
}
