// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CanonicalSportsEvent } from "./CanonicalSportsEvent.js";
import { SportsMatchingLookupResult } from "./SportsMatchingLookupResult.js";
import { SportsMatchingSnapshot } from "./SportsMatchingSnapshot.js";

export const SportsMatchingLookupResponse: core.serialization.ObjectSchema<
    serializers.SportsMatchingLookupResponse.Raw,
    PredictorSDK.SportsMatchingLookupResponse
> = core.serialization.object({
    data: core.serialization.list(CanonicalSportsEvent),
    lookups: core.serialization.record(core.serialization.string(), SportsMatchingLookupResult),
    snapshot: SportsMatchingSnapshot,
});

export declare namespace SportsMatchingLookupResponse {
    export interface Raw {
        data: CanonicalSportsEvent.Raw[];
        lookups: Record<string, SportsMatchingLookupResult.Raw>;
        snapshot: SportsMatchingSnapshot.Raw;
    }
}
