// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { CanonicalSportsEvent } from "./CanonicalSportsEvent.js";
import { PaginationBlock } from "./PaginationBlock.js";
import { SportsMatchingSnapshot } from "./SportsMatchingSnapshot.js";

export const SportsMatchingResponse: core.serialization.ObjectSchema<
    serializers.SportsMatchingResponse.Raw,
    PredictorSDK.SportsMatchingResponse
> = core.serialization.object({
    canonicalEvents: core.serialization.property(
        "canonical_events",
        core.serialization.record(core.serialization.string(), CanonicalSportsEvent),
    ),
    pagination: PaginationBlock.optional(),
    snapshot: SportsMatchingSnapshot,
});

export declare namespace SportsMatchingResponse {
    export interface Raw {
        canonical_events: Record<string, CanonicalSportsEvent.Raw>;
        pagination?: PaginationBlock.Raw | null;
        snapshot: SportsMatchingSnapshot.Raw;
    }
}
