// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { UnifiedMarketProvider } from "./UnifiedMarketProvider.js";

export const UnifiedMarket: core.serialization.ObjectSchema<serializers.UnifiedMarket.Raw, PredictorSDK.UnifiedMarket> =
    core.serialization.object({
        id: core.serialization.string(),
        provider: UnifiedMarketProvider,
        title: core.serialization.string(),
    });

export declare namespace UnifiedMarket {
    export interface Raw {
        id: string;
        provider: UnifiedMarketProvider.Raw;
        title: string;
    }
}
