// This file was auto-generated by Fern from our API Definition.

import type * as PredictorSDK from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const UnifiedMarketProvider: core.serialization.Schema<
    serializers.UnifiedMarketProvider.Raw,
    PredictorSDK.UnifiedMarketProvider
> = core.serialization.enum_(["kalshi", "polymarket", "predict", "sxbet"]);

export declare namespace UnifiedMarketProvider {
    export type Raw = "kalshi" | "polymarket" | "predict" | "sxbet";
}
