// This file was auto-generated by Fern from our API Definition.

export const PredictorSDKEnvironment = {
    Production: "https://api.predictorsdk.com",
} as const;

export type PredictorSDKEnvironment = typeof PredictorSDKEnvironment.Production;
